import numpy as np


class FaceEncoder:
    """Extract face embeddings."""

    def get_embedding(self, face):
        """
        Returns a 512-dimensional embedding
        generated by InsightFace.
        """

        return np.array(face.embedding)